{{- $selectorLabels := include "db-instances.selectorLabels" .}}
{{- $operatorNs := include "db-instances.operatorNs" . -}}
{{- if .Values.dbinstances }}
{{- range $name, $value := .Values.dbinstances }}
---
apiVersion: "kci.rocks/v1alpha1"
kind: "DbInstance"
metadata:
  name: {{ $name }}
  annotations:
    {{- if $value.google }}
    checksum/config: {{ $value.google.configMap.data | sha256sum }}
    {{- end }}
  labels:
    {{- include "db-instances.labels" $ | nindent 4 }}
spec:
  engine: {{ $value.engine }}
  {{- if $value.existingAdminSecret }}
  adminSecretRef:
    Namespace: {{ $value.existingAdminSecret.namespace }}
    Name: {{ $value.existingAdminSecret.name }}
  {{- else }}
  adminSecretRef:
    Namespace: {{ $operatorNs }}
    Name: {{ $name }}-admin-secret
  {{- end }}
  {{- if $value.backup }}
  backup:
{{ toYaml $value.backup | indent 4 }}
  {{- end }}
  monitoring:
    enabled: {{ $value.monitoring.enabled }}
  {{- if $value.sslConnection }}
  sslConnection:
    enabled: {{ $value.sslConnection.enabled }}
    skip-verify: {{ $value.sslConnection.skipVerify }}
  {{- end }}
  {{- if $value.google }}
  google:
    instance: {{ $value.google.instanceName }}
    configmapRef:
      Namespace: {{ $operatorNs }}
      Name: {{ $name }}-config
  {{- if $value.google.clientSecret }}
    clientSecretRef:
      Namespace: {{ $operatorNs }}
      Name: {{ $name }}-client-secret
  {{- end }}
  {{- end }}
  {{- if $value.generic }}
  generic:
    host: {{ $value.generic.host }}
    port: {{ $value.generic.port }}
  {{- if $value.generic.publicIp }}
    publicIp: {{ $value.generic.publicIp }}
  {{- end }}
  {{- if $value.generic.backupHost }}
    backupHost: {{ $value.generic.backupHost }}
  {{- end }}
  {{- end }}
{{- if not $value.existingAdminSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-admin-secret
  namespace: {{ $operatorNs }}
  labels:
    {{ include "db-instances.labels" $ | nindent 4 }}
type: Opaque
data:
  user: {{ $value.secrets.adminUser | b64enc }}
  password: {{ $value.secrets.adminPassword | b64enc }}
{{- end }}
---
{{- if $value.google }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $operatorNs }}
  labels:
    {{- include "db-instances.labels" $ | nindent 4 }}
data:
  config: |
{{ $value.google.configMap.data | indent 4 }}
{{- if $value.google.clientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-client-secret
  namespace: {{ $operatorNs }}
  labels:
    {{- include "db-instances.labels" $ | nindent 4 }}
data:
  credentials.json: |-
{{ $value.google.clientSecret | b64enc | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
