{{- if .Values.secrets }}
{{- if .Values.secrets.gsql }}
# secret which is required for creating database (used by db-operator)
# required permission (Cloud SQL Admin)
# cloudsql.instances.create
# cloudsql.instances.get
# cloudsql.instances.update
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-admin-serviceaccount
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{ .Values.secrets.gsql.admin | b64enc }}
{{- if .Values.secrets.gsql.readonly }}
---
# secret which is required for connecting/accessing to database (used by cloudproxy of application)
# required permission (Cloud SQL Client)
# cloudsql.instances.connect
# cloudsql.instances.get
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-readonly-serviceaccount
  labels:
    {{- include "db-operator.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{ .Values.secrets.gsql.readonly | b64enc }}
{{- end }}
{{- end }}
{{- end }}